version: '3'
services:
 docker-app:
    image: felipelima/docker/crud-springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - docker-mongodb
 docker-mongodb:
    image: mongo
    ports:
       - "27017:27017"   